name: scrollable_list_tab_scroller
description: Customizable Flutter widget that synchronizes a scrollable list of grouped items with tabs
version: 2.0.1

environment:
  sdk: ^3.3.0

repository: https://github.com/railson-ferreira/scrollable_list_tab_scroller

dependencies:
  flutter:
    sdk: flutter
  scrollable_positioned_list: ^0.3.8
  scrolls_to_top: ">=1.0.0 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^4.0.0
